/* Generated By:JavaCC: Do not edit this line. DSLProjectConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface DSLProjectConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NUMBER = 4;
  /** RegularExpression Id. */
  int ARRAY = 5;
  /** RegularExpression Id. */
  int VARIABLE = 6;
  /** RegularExpression Id. */
  int DIGIT = 7;
  /** RegularExpression Id. */
  int BS = 8;
  /** RegularExpression Id. */
  int EOL = 9;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "<NUMBER>",
    "<ARRAY>",
    "<VARIABLE>",
    "<DIGIT>",
    "<BS>",
    "\"\\n\"",
    "\"+\"",
    "\"-\"",
    "\"=\"",
  };

}
